# Generated by Django 4.2.3 on 2023-08-21 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atividade', '0002_atividade_lista_atividade_texto'),
        ('tarefa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefa',
            name='atividadePrincipal',
        ),
        migrations.AddField(
            model_name='tarefa',
            name='atividade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='atividade.atividade'),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='texto',
            field=models.TextField(default=' '),
        ),
    ]
