# Generated by Django 4.2.3 on 2023-08-21 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0003_lista_texto'),
        ('atividade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='lista',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lista.lista'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='texto',
            field=models.TextField(default=' '),
        ),
    ]
