# Generated by Django 4.2.3 on 2023-08-24 02:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atividade', '0004_alter_atividade_datafim_alter_atividade_datainicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='texto',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
